### ISSUE TITLE
Respect newlines when calculating boundary box

### ISSUE THREAD

**Issue by basxto** [ameyrk99/dvdts#5]
I ran `dvdts -a -t "$(figlet CCC-FFM)"` and it just counted the string length.
Instead it should count the lines and the length of the longest line.

![](https://basxto.de/iae4o5_screenshots/2020-01-11_23:39_1920x1060.png)

**Comment by ameyrk99** [comment]
Thanks for noticing the issue and the PR.

I think it would actually be better to use something like figlet by default because the terminal text tends to be too small unless you increase it. I will start working on that.

**Comment by basxto** [comment]
Well, I think that would lack quite some flexibility.
What would be interesting is:
* `-c none`
* ignore ANSI escape codes when calculating length
* allow to pipe output of another program

With that you could do things like:
`toilet -f smmono9 --rainbow CCC-FFM | dvdts -c none`
`ponysay --ponyonly -f owl | dvdts -c none`

**Comment by ameyrk99** [comment]
#7
