### ISSUE TITLE
Add support for piping input 

### ISSUE THREAD

**Issue by ameyrk99** [ameyrk99/dvdts#7]
- add flags `- c none` or `- p`, or check for piped input and ignore text
-  ignore ANSI escape codes when calculating length
- allow to pipe output of another program

So that one can use something like `ponysay --ponyonly -f owl | dvdts -c none` or `cowsay Hello, World | dvdts -p`

**Comment by K0-RR** [comment]
Is this implemented?
Piping doesn't work and -p returns `flag provided but not defined: -p`

**Comment by ameyrk99** [comment]
Yes it is

Try something like `cowsay Hello World | dvdts` for example
